export {
    getData,
    postData,
    GET_SMURF_DATA_REQUEST,
    GET_SMURF_DATA_SUCCESS,
    GET_SMURF_DATA_FAILURE,
    POST_SMURF_DATA_REQUEST,
    POST_SMURF_DATA_SUCCESS,
    POST_SMURF_DATA_FAILURE
  } from './SmurfsAction';
